global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['fastapi:8000']

  - job_name: 'neo4j'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['neo4j:7474']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
