"""Create project and knowledge graph tables

Revision ID: 5af95ab80f1a
Revises: 
Create Date: 2025-04-20 15:24:03.540512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af95ab80f1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('creator_email', sa.String(length=255), nullable=True),
        sa.Column('authorization_group', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_authorization_group'), 'projects', ['authorization_group'], unique=False)
    op.create_index(op.f('ix_projects_creator_email'), 'projects', ['creator_email'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    
    op.create_table('knowledge_graphs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('creator_email', sa.String(length=255), nullable=True),
        sa.Column('project_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_graphs_creator_email'), 'knowledge_graphs', ['creator_email'], unique=False)
    op.create_index(op.f('ix_knowledge_graphs_id'), 'knowledge_graphs', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_graphs_name'), 'knowledge_graphs', ['name'], unique=False)
    
    op.create_table('project_kg_association',
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('kg_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['kg_id'], ['knowledge_graphs.id'], ),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.PrimaryKeyConstraint('project_id', 'kg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_kg_association')
    op.drop_index(op.f('ix_knowledge_graphs_name'), table_name='knowledge_graphs')
    op.drop_index(op.f('ix_knowledge_graphs_id'), table_name='knowledge_graphs')
    op.drop_index(op.f('ix_knowledge_graphs_creator_email'), table_name='knowledge_graphs')
    op.drop_table('knowledge_graphs')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_creator_email'), table_name='projects')
    op.drop_index(op.f('ix_projects_authorization_group'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
